// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fotoservice.data;

#nullable disable

namespace fotoservice.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("fotoservice.data.models.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Familie")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Quality")
                        .HasColumnType("longtext");

                    b.Property<string>("Series")
                        .HasColumnType("longtext");

                    b.Property<string>("Spare1")
                        .HasColumnType("longtext");

                    b.Property<string>("Spare2")
                        .HasColumnType("longtext");

                    b.Property<string>("Spare3")
                        .HasColumnType("longtext");

                    b.Property<int>("YearTaken")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
